config.clientSpawn = false
config.clientSpawnForced = {
    ['paredao'] = true
}

config.taxSafe = 0.02
config.taxDetained = 0.03
config.taxIPVA = 0.05
config.ipvaDays = 7

config.vehicles = {
------------------------------------------------------------------------------------------------------------------------
-- VIP
------------------------------------------------------------------------------------------------------------------------
    ['h2carb'] = { name = 'Ninja H2 Carb.', maker = 'Kawasaki', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['r34bluedragon'] = { name = 'Skyline Dragon', maker = 'Nissan', price = 1000000, trunk = 40, glove = 15, type = 'vip', class = 'super', banned = false },
    ['velar'] = { name = 'velar', maker = 'Land Rover', price = 1000000, trunk = 50, glove = 15, type = 'vip', class = 'suvs', banned = false },
    ['458spider'] = { name = 'Spider', maker = 'Ferrari', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'super', banned = false },
    ['audirs6'] = { name = 'RS6', maker = 'Audi', price = 1000000, trunk = 50, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['rmodrs6'] = { name = 'RS6 G2', maker = 'Audi', price = 1000000, trunk = 50, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['r1200'] = { name = 'R1250', maker = 'BMW', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['babyhuracan'] = { name = 'Baby Huracan', maker = 'Lamborghini', price = 1000000, trunk = 0, glove = 0, type = 'vip', class = 'super', banned = false },
    ['bmwm4gts'] = { name = 'M4 GTS', maker = 'BMW', price = 1000000, trunk = 50, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['monalisa'] = { name = 'Monalisa', maker = 'Nissan', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['hornet'] = { name = 'Hornet', maker = 'Honda', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['a80'] = { name = 'Supra', maker = 'Toyota', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['sennagtr'] = { name = 'Senna', maker = 'Mclaren', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'super', banned = false },
    ['urus'] = { name = 'Urus', maker = 'Lamborghini', price = 1000000, trunk = 50, glove = 15, type = 'vip', class = 'suvs', banned = false },
    ['ferrariitalia'] = { name = 'Italia 478', maker = 'Ferrari', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'super', banned = false },
    ['maxima22'] = { name = 'Nissan maxima', maker = 'Nissan', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['bmwe39'] = { name = 'Bmw e39', maker = 'Bmw', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'super', banned = false },
    ['370zrubytiger'] = { name = '370z', maker = 'Nissan', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'super', banned = false },
    ['jeslbwk'] = { name = 'Jesko', maker = 'Koenigsegg', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['720s18'] = { name = 'Mclaren 720s', maker = 'McLaren', price = 1000, trunk = 20, glove = 15, type = 'vip', class = 'super', banned = false },
    ['rmodgt63'] = { name = 'GT 63', maker = 'Mercedes-Benz', price = 1000000, trunk = 50, glove = 15, type = 'vip', class = 'super', banned = false },
    ['rmodr8c'] = { name = 'R8 Conv.', maker = 'Audi', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'super', banned = false },
    ['tiger'] = { name = 'Tiger', maker = 'Triumph', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['21Charscat'] = { name = 'Mustang', maker = 'Ford Mustang', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['lanex400'] = { name = 'Lancer E. X', maker = 'Mitsubishi', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['lancer9'] = { name = 'Lancer E. 9', maker = 'Mitsubishi', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['xxxxx'] = { name = 'Monster 6X6', maker = 'Mercedes-Benz', price = 1200000, trunk = 200, glove = 15, type = 'vip', class = 'offroad', banned = false },
    ['ym1'] = { name = 'Race M1', maker = 'Yamaha', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['6x6ev'] = { name = '6x6 EV', maker = 'Hummer', price = 1000000, trunk = 150, glove = 15, type = 'vip', class = 'offroad', banned = false },
    ['rmodskyline34'] = { name = 'SkyLineR34 G2', maker = 'Nissan', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['nissanskyliner34'] = { name = 'Skyline R34', maker = 'Nissan', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['auditt'] = { name = 'Audi TT', maker = 'Audi', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'super', banned = false },
    ['911r'] = { name = '911R', maker = 'Porsche', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'super', banned = false },
    ['bmws'] = { name = 'S1000rr', maker = 'Bmw', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['mt09black'] = { name = 'Mt09', maker = 'Yamaha', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['hbocnetrongt'] = { name = 'Audi R8', maker = 'Audi', price = 1000000, trunk = 0, glove = 0, type = 'vip', class = 'super', banned = false },
    ['babyr34'] = { name = 'Baby R34', maker = 'Nissan', price = 1000000, trunk = 0, glove = 0, type = 'vip', class = 'super', banned = false },
    ['q820'] = { name = 'Audi Q8', maker = 'Audi', price = 1000000, trunk = 50, glove = 15, type = 'vip', class = 'suvs', banned = false },
    ['zn20'] = { name = 'TSR-GT', maker = 'Zenvo', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'super', banned = false },
    ['g7cross'] = { name = 'Saveiro', maker = 'Volkswagen', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'super', banned = false },
    ['r1250baby'] = { name = 'Baby R1250', maker = 'Bmw', price = 1000000, trunk = 0, glove = 0, type = 'vip', class = 'motorcycles', banned = false },
    ['cbb'] = { name = 'Cb1000R', maker = 'Honda', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['nis15'] = { name = 'Silvia 15', maker = 'Nissan', price = 1000000, trunk = 35, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['teslaprior'] = { name = 'Prior', maker = 'Tesla', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['babyjesko'] = { name = 'Baby Jesko', maker = 'Koenigsegg', price = 1000000, trunk = 0, glove = 0, type = 'vip', class = 'super', banned = false },
    ['ram1500'] = { name = 'Ram', maker = 'Dodge Ram', price = 1000000, trunk = 50, glove = 15, type = 'vip', class = 'suvs', banned = false },
    ['rmodgtr50'] = { name = 'GTR 50', maker = 'Nissan', price = 1000000, trunk = 40, glove = 15, type = 'vip', class = 'super', banned = false },
    ['z1000'] = { name = 'Z1000', maker = 'Kawasaki', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['xj6'] = { name = 'XJ-6', maker = 'Yamaha', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['africat'] = { name = 'CRF 1000 Africa', maker = 'Honda', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['tenere1200'] = { name = 'Tenere 12000', maker = 'Yamaha', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'motorcycles', banned = false },
    ['fk8'] = { name = 'FK8', maker = 'Honda', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['rmodmi8lb'] = { name = 'I8 libert walker', maker = 'BMW', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'super', banned = false },
    ['m40i'] = { name = 'Bmw M40i', maker = 'Bmw', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['merc23'] = { name = 'Mercedes E-class', maker = 'Mercedes-Benz', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['foxct'] = { name = 'Cybertruck', maker = 'Tesla', price = 1000000, trunk = 100, glove = 15, type = 'vip', class = 'offroad', banned = false },
    ['babym4conversible'] = { name = 'Baby M4', maker = 'Bmw', price = 1000000, trunk = 0, glove = 0, type = 'vip', class = 'super', banned = false },
    ['rmodbolide'] = { name = 'Bolide W16', maker = 'Bugatti', price = 1000000, trunk = 40, glove = 15, type = 'vip', class = 'super', banned = false },
    ['amarok'] = { name = 'Amarok', maker = 'Volkswagen', price = 1000000, trunk = 150, glove = 15, type = 'vip', class = 'offroad', banned = false },
    ['rmodgt63mini'] = { name = 'Baby Mercedes', maker = 'Mercedes-Benz', price = 1000000, trunk = 0, glove = 0, type = 'vip', class = 'super', banned = false },
    ['19raptor'] = { name = 'Raptor', maker = 'Ford', price = 1000000, trunk = 100, glove = 15, type = 'vip', class = 'offroad', banned = false },
    ['golfrebaixado'] = { name = 'Golf Rebaixado', maker = 'Volkswagen', price = 65000, trunk = 30, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['gxlaferrari'] = { name = 'Laferrari', maker = 'Ferrari', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'sports', banned = false },
    ['bmwi8'] = { name = 'i8', maker = 'BMW', price = 1000000, trunk = 20, glove = 15, type = 'vip', class = 'super', banned = false },
    ['nissanr33tbk'] = { name = 'skyline r33', maker = 'Nissan', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'super', banned = false },
    ['718b'] = { name = '718B', maker = 'Porsche', price = 1000000, trunk = 30, glove = 15, type = 'vip', class = 'super', banned = false },
------------------------------------------------------------------------------------------------------------------------
-- CARS
------------------------------------------------------------------------------------------------------------------------
    ['rcbandito'] = { name = 'RC Bandito', maker = 'Rockstar', price = 1000000, trunk = 1000, glove = 15, type = 'rental', class = 'offroad', banned = false },
    ['kuruma'] = { name = 'Kuruma', maker = 'Karin', price = 375000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['trophytruck2'] = { name = 'Trophytruck2', maker = 'Vapid', price = 400000, trunk = 20, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['rhapsody'] = { name = 'Rhapsody', maker = 'Declasse', price = 10000, trunk = 30, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['vacca'] = { name = 'Vacca', maker = 'Pegassi', price = 350000, trunk = 30, glove = 15, type = 'cars', class = 'super', banned = false },
    ['pounder'] = { name = 'Pounder (5-Ton)', maker = 'MTL', price = 1000000, trunk = 5000, glove = 15, type = 'cars', class = 'commercial', banned = false },
    ['massacro'] = { name = 'Massacro', maker = 'Dewbauchee', price = 330000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['dominator7'] = { name = 'Dominator7', maker = 'Vapid', price = 355000, trunk = 30, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['moonbeam'] = { name = 'Moonbeam', maker = 'Declasse', price = 220000, trunk = 80, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['bfinjection'] = { name = 'Bfinjection', maker = 'Bf', price = 80000, trunk = 100, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['entity2'] = { name = 'Entity2', maker = 'överflöd', price = 550000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['deviant'] = { name = 'Deviant', maker = 'Schyster', price = 370000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['pounder2'] = { name = 'Pounder2 (1.2-Ton)', maker = 'MTL', price = 1000000, trunk = 1200, glove = 15, type = 'cars', class = 'commercial', banned = false },
    ['weevil'] = { name = 'weevil', maker = 'BF', price = 110000, trunk = 30, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['granger'] = { name = 'Granger', maker = 'Declasse', price = 345000, trunk = 100, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['buffalo'] = { name = 'Buffalo', maker = 'Bravado', price = 300000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['gresley'] = { name = 'Gresley', maker = 'Bravado', price = 150000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['penetrator'] = { name = 'Penetrator', maker = 'Ocelot', price = 480000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['faction3'] = { name = 'Faction3', maker = 'Willard', price = 350000, trunk = 60, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['limo2'] = { name = 'limo2', maker = 'Benefactor', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['vstr'] = { name = 'vstr', maker = 'Albany', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['dominator3'] = { name = 'Dominator3', maker = 'Vapid', price = 305000, trunk = 30, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['penumbra'] = { name = 'Penumbra', maker = 'Maibatsu', price = 150000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['blade'] = { name = 'Blade', maker = 'Vapid', price = 110000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['raiden'] = { name = 'Raiden', maker = 'Coil', price = 240000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['baller3'] = { name = 'Baller3', maker = 'Gallivanter', price = 175000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['monster4'] = { name = 'Monster', maker = 'Bravado', price = 1000000, trunk = 0, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['hotring'] = { name = 'Hotring', maker = 'Declasse', price = 300000, trunk = 60, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['seminole'] = { name = 'Seminole', maker = 'Canis', price = 110000, trunk = 60, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['btype3'] = { name = 'Btype3', maker = 'Albany', price = 100000, trunk = 40, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['tulip'] = { name = 'Tulip', maker = 'Declasse', price = 200000, trunk = 60, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['windsor2'] = { name = 'Windsor2', maker = 'Enus', price = 200000, trunk = 40, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['sugoi'] = { name = 'sugoi', maker = 'Dinka', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['kanjo'] = { name = 'Kanjo', maker = 'Dinka', price = 110000, trunk = 30, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['italigtb'] = { name = 'Italigtb', maker = 'Progen', price = 600000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['comet2'] = { name = 'Comet2', maker = 'Pfister', price = 250000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['emperor2'] = { name = 'Emperor 2', maker = 'Albany', price = 50000, trunk = 60, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['krieger'] = { name = 'krieger', maker = 'Benefactor', price = 400000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['dubsta2'] = { name = 'Dubsta2', maker = 'Benefactor', price = 240000, trunk = 70, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['glendale'] = { name = 'Glendale', maker = 'Benefactor', price = 70000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['autarch'] = { name = 'Autarch', maker = 'överflöd', price = 760000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['ingot'] = { name = 'Ingot', maker = 'Vulcar', price = 160000, trunk = 60, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['sentinel3'] = { name = 'Sentinel3', maker = 'Übermacht', price = 70000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['furoregt'] = { name = 'Furoregt', maker = 'Lampadati', price = 290000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['tyrant'] = { name = 'Tyrant', maker = 'överflöd', price = 650000, trunk = 30, glove = 15, type = 'cars', class = 'super', banned = false },
    ['burrito3'] = { name = 'Burrito3', maker = 'Declasse', price = 260000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['riata'] = { name = 'Riata', maker = 'Vapid', price = 250000, trunk = 80, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['imorgon'] = { name = 'imorgon', maker = 'Överflöd', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['adder'] = { name = 'Adder', maker = 'Truffade', price = 620000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['zion2'] = { name = 'Zion2', maker = 'Übermacht', price = 60000, trunk = 40, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['rapidgt2'] = { name = 'Rapidgt2', maker = 'Dewbauchee', price = 300000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['schafter4'] = { name = 'Schafter4', maker = 'Benefactor', price = 125000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['rumpo2'] = { name = 'Rumpo2', maker = 'Bravado', price = 260000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = true },
    ['paragon'] = { name = 'paragon', maker = 'Enus', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['comet5'] = { name = 'Comet5', maker = 'Pfister', price = 300000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['cavalcade2'] = { name = 'Cavalcade2', maker = 'Albany', price = 130000, trunk = 60, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['zion'] = { name = 'Zion', maker = 'Übermacht', price = 50000, trunk = 50, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['gauntlet3'] = { name = 'Gauntlet3', maker = 'Bravado', price = 195000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['dloader'] = { name = 'Dloader', maker = 'Bravado', price = 150000, trunk = 80, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['windsor'] = { name = 'Windsor', maker = 'Enus', price = 150000, trunk = 20, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['pigalle'] = { name = 'Pigalle', maker = 'Lampadati', price = 250000, trunk = 60, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['bullet'] = { name = 'Bullet', maker = 'Vapid', price = 400000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['asea'] = { name = 'Asea', maker = 'Declasse', price = 55000, trunk = 30, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['brawler'] = { name = 'Brawler', maker = 'Coil', price = 250000, trunk = 50, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['tailgater'] = { name = 'Tailgater', maker = 'Obey', price = 110000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['rebla'] = { name = 'Rebla', maker = 'Übermacht', price = 500000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['voodoo2'] = { name = 'Voodoo2', maker = 'Declasse', price = 220000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['massacro2'] = { name = 'Massacro2', maker = 'Dewbauchee', price = 330000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['rapidgt'] = { name = 'Rapidgt', maker = 'Dewbauchee', price = 250000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['dubsta'] = { name = 'Dubsta', maker = 'Benefactor', price = 210000, trunk = 70, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['deveste'] = { name = 'Deveste', maker = 'Principe', price = 1000000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['fagaloa'] = { name = 'Fagaloa', maker = 'Vulcar', price = 320000, trunk = 80, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['dynasty'] = { name = 'Dynasty', maker = 'Weeny', price = 250000, trunk = 40, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['banshee'] = { name = 'Banshee', maker = 'Bravado', price = 300000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['habanero'] = { name = 'Habanero', maker = 'Emperor', price = 110000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['futo2'] = { name = 'futo2', maker = 'Karin', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['radi'] = { name = 'Radi', maker = 'Vapid', price = 110000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['blista3'] = { name = 'Blista3', maker = 'Dinka', price = 80000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['tampa'] = { name = 'Tampa', maker = 'Declasse', price = 170000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['oracle2'] = { name = 'Oracle2', maker = 'Ubermacht', price = 80000, trunk = 60, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['jester3'] = { name = 'Jester3', maker = 'Dinka', price = 345000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['bodhi2'] = { name = 'Bodhi2', maker = 'Canis', price = 170000, trunk = 90, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['exemplar'] = { name = 'Exemplar', maker = 'Dewbauchee', price = 80000, trunk = 20, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['schlagen'] = { name = 'Schlagen', maker = 'Benefactor', price = 690000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['nero2'] = { name = 'Nero2', maker = 'Truffade', price = 480000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['jester4'] = { name = 'Jester4', maker = 'Dinka', price = 645000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['ellie'] = { name = 'Ellie', maker = 'Vapid', price = 320000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['blista'] = { name = 'Blista', maker = 'Dinka', price = 17500, trunk = 40, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['toreador'] = { name = 'toreador', maker = 'Pegassi', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['rapidgt3'] = { name = 'Rapidgt3', maker = 'Dewbauchee', price = 200000, trunk = 40, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['impaler'] = { name = 'Impaler', maker = 'Declasse', price = 320000, trunk = 60, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['sultan'] = { name = 'Sultan', maker = 'Karin', price = 210000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['sc1'] = { name = 'Sc1', maker = 'Übermacht', price = 495000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['ruston'] = { name = 'Ruston', maker = 'Hijak', price = 370000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['lynx'] = { name = 'Lynx', maker = 'Ocelot', price = 370000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['bjxl'] = { name = 'Bjxl', maker = 'Karin', price = 110000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['sentinel2'] = { name = 'Sentinel2', maker = 'Übermacht', price = 60000, trunk = 40, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['bestiagts'] = { name = 'Bestiagts', maker = 'Grotti', price = 500000, trunk = 60, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['moonbeam2'] = { name = 'Moonbeam2', maker = 'Declasse', price = 250000, trunk = 70, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['tropos'] = { name = 'Tropos', maker = 'Lampadati', price = 170000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['previon'] = { name = 'Previon', maker = 'Karin', price = 145000, trunk = 30, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['retinue'] = { name = 'Retinue', maker = 'Vapid', price = 150000, trunk = 40, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['stratum'] = { name = 'Stratum', maker = 'Zirconium', price = 90000, trunk = 70, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['gauntlet4'] = { name = 'Gauntlet4', maker = 'Bravado', price = 215000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['baller'] = { name = 'Baller', maker = 'Gallivanter', price = 150000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['khamelion'] = { name = 'Khamelion', maker = 'Hijak', price = 210000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['nebula'] = { name = 'Nebula', maker = 'Vulcar', price = 180000, trunk = 30, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['btype2'] = { name = 'Btype2', maker = 'Albany', price = 460000, trunk = 20, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['phoenix'] = { name = 'Phoenix', maker = 'Imponte', price = 250000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['pony'] = { name = 'Pony', maker = 'Brute', price = 260000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['stalion2'] = { name = 'Stalion2', maker = 'Declasse', price = 150000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['schwarzer'] = { name = 'Schwarzer', maker = 'Benefactor', price = 170000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['jugular'] = { name = 'Jugular', maker = 'Ocelot', price = 720000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['comet3'] = { name = 'Comet3', maker = 'Pfister', price = 290000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['club2'] = { name = 'Club2', maker = 'Bf', price = 60000, trunk = 25, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['novak'] = { name = 'Novak', maker = 'Lampadati', price = 490000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['virgo2'] = { name = 'Virgo2', maker = 'Dundreary', price = 250000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['vagner'] = { name = 'Vagner', maker = 'Dewbauchee', price = 350000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['baller6'] = { name = 'Baller6', maker = 'Gallivanter', price = 280000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['oracle'] = { name = 'Oracle', maker = 'Ubermacht', price = 60000, trunk = 50, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['virtue'] = { name = 'virtue', maker = 'Ocelot', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Super', banned = false },
    ['hotknife'] = { name = 'Hotknife', maker = 'Vapid', price = 180000, trunk = 30, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['brioso'] = { name = 'Brioso', maker = 'Grotti', price = 25000, trunk = 30, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['alpha'] = { name = 'Alpha', maker = 'Albany', price = 230000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['minivan'] = { name = 'Minivan', maker = 'Vapid', price = 110000, trunk = 70, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['surfer'] = { name = 'Surfer', maker = 'Bf', price = 150000, trunk = 80, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['brutus'] = { name = 'brutus', maker = 'Declasse', price = 110000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['stinger'] = { name = 'Stinger', maker = 'Grotti', price = 220000, trunk = 20, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['sultan3'] = { name = 'sultan3', maker = 'Karin', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['prototipo'] = { name = 'Prototipo', maker = 'Grotti', price = 1000000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['gauntlet'] = { name = 'Gauntlet', maker = 'Bravado', price = 165000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['f620'] = { name = 'F620', maker = 'Ocelot', price = 55000, trunk = 30, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['intruder'] = { name = 'Intruder', maker = 'Karin', price = 60000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['chino'] = { name = 'Chino', maker = 'Vapid', price = 100000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['cyclone'] = { name = 'Cyclone', maker = 'Coil', price = 920000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['huntley'] = { name = 'Huntley', maker = 'Enus', price = 110000, trunk = 60, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['pony2'] = { name = 'Pony2', maker = 'Brute', price = 260000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['pbus2'] = { name = 'Ônibus Festival', maker = 'Vapid', price = 1000000, trunk = 0, glove = 15, type = 'cars', class = 'service', banned = false },
    ['lurcher'] = { name = 'Lurcher', maker = 'Albany', price = 150000, trunk = 60, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['flashgt'] = { name = 'Flashgt', maker = 'Vapid', price = 370000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['jb700'] = { name = 'Jb700', maker = 'Dewbauchee', price = 220000, trunk = 30, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['italigto'] = { name = 'Italigto', maker = 'Grotti', price = 800000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['futo'] = { name = 'Futo', maker = 'Karin', price = 170000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['infernus2'] = { name = 'Infernus2', maker = 'Pegassi', price = 450000, trunk = 20, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['fusilade'] = { name = 'Fusilade', maker = 'Schyster', price = 210000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['sabregt2'] = { name = 'Sabregt2', maker = 'Declasse', price = 150000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['baller2'] = { name = 'Baller2', maker = 'Gallivanter', price = 160000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['cavalcade'] = { name = 'Cavalcade', maker = 'Albany', price = 110000, trunk = 60, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['michelli'] = { name = 'Michelli', maker = 'Lampadati', price = 90000, trunk = 40, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['patriot2'] = { name = 'Patriot2', maker = 'Mammoth', price = 550000, trunk = 60, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['virgo3'] = { name = 'Virgo3', maker = 'Dundreary', price = 180000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['carbonizzare'] = { name = 'Carbonizzare', maker = 'Grotti', price = 290000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['cheburek'] = { name = 'Cheburek', maker = 'Rune', price = 170000, trunk = 50, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['everon'] = { name = 'Everon', maker = 'Karin', price = 700000, trunk = 100, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['cypher'] = { name = 'Cypher', maker = 'Übermacht', price = 980000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['gauntlet2'] = { name = 'Gauntlet2', maker = 'Bravado', price = 165000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['landstalker'] = { name = 'Landstalker', maker = 'Dundreary', price = 130000, trunk = 70, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['streiter'] = { name = 'Streiter', maker = 'Benefactor', price = 250000, trunk = 70, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['coquette3'] = { name = 'Coquette3', maker = 'Invetero', price = 195000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['stingergt'] = { name = 'Stingergt', maker = 'Grotti', price = 230000, trunk = 20, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['stalion'] = { name = 'Stalion', maker = 'Classique', price = 150000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['omnis'] = { name = 'Omnis', maker = 'Obey', price = 240000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['sentinel'] = { name = 'Sentinel', maker = 'Übermacht', price = 50000, trunk = 50, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['sultanrs'] = { name = 'Sultan RS', maker = 'Karin', price = 450000, trunk = 30, glove = 15, type = 'cars', class = 'super', banned = false },
    ['kamacho'] = { name = 'Kamacho', maker = 'Canis', price = 350000, trunk = 90, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['cheetah2'] = { name = 'Cheetah2', maker = 'Grotti', price = 240000, trunk = 20, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['menacer'] = { name = 'menacer', maker = 'HVY', price = 700000, trunk = 30, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['deluxo'] = { name = 'deluxo', maker = 'Imponte', price = 400000, trunk = 20, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['voodoo'] = { name = 'Voodoo', maker = 'Declasse', price = 220000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['elegy'] = { name = 'Elegy', maker = 'Annis', price = 350000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['speedo4'] = { name = 'speedo4', maker = 'Vapid', price = 220000, trunk = 100, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['youga3'] = { name = 'youga3', maker = 'Bravado', price = 220000, trunk = 100, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['vigilante'] = { name = 'vigilante', maker = 'Grotti', price = 400000, trunk = 0, glove = 15, type = 'cars', class = 'super', banned = false },
    ['viseris'] = { name = 'viseris', maker = 'Lampadati', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['stromberg'] = { name = 'stromberg', maker = 'Ocelot', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['seminole2'] = { name = 'seminole2', maker = 'Canis', price = 400000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['burrito2'] = { name = 'Burrito2', maker = 'Declasse', price = 500000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['coquette4'] = { name = 'coquette4', maker = 'Invetero', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['yosemite'] = { name = 'Yosemite', maker = 'Declasse', price = 350000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['felon'] = { name = 'Felon', maker = 'Lampadati', price = 70000, trunk = 50, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['sheava'] = { name = 'Sheava', maker = 'Emperor', price = 700000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['turismor'] = { name = 'Turismor', maker = 'Grotti', price = 700000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['visione'] = { name = 'Visione', maker = 'Grotti', price = 650000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['virgo'] = { name = 'Virgo', maker = 'Albany', price = 150000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['panto'] = { name = 'Panto', maker = 'Benefactor', price = 5000, trunk = 20, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['rumpo'] = { name = 'Rumpo', maker = 'Bravado', price = 400000, trunk = 180, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['ruiner'] = { name = 'Ruiner', maker = 'Imponte', price = 150000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['coquette'] = { name = 'Coquette', maker = 'Invetero', price = 250000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['zr350'] = { name = 'zr350', maker = 'Annis', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['phantom3'] = { name = 'Phantom', maker = 'Jobuilt', price = 1000000, trunk = 0, glove = 15, type = 'cars', class = 'commercial', banned = false },
    ['rallytruck'] = { name = 'RallyTruck', maker = 'MTL', price = 260000, trunk = 400, glove = 15, type = 'cars', class = 'service', banned = false },
    ['dukes'] = { name = 'Dukes', maker = 'Imponte', price = 150000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['picador'] = { name = 'Picador', maker = 'Cheval', price = 150000, trunk = 90, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['slamvan3'] = { name = 'Slamvan3', maker = 'Vapid', price = 230000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['mule2'] = { name = 'Mule2', maker = 'Maibatsu', price = 1000000, trunk = 400, glove = 15, type = 'cars', class = 'commercial', banned = false },
    ['minivan2'] = { name = 'Minivan2', maker = 'Vapid', price = 220000, trunk = 60, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['growler'] = { name = 'growler', maker = 'Pfister', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['komoda'] = { name = 'komoda', maker = 'Lampadati', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['panthere'] = { name = 'panthere', maker = 'Toundra', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['paragon2'] = { name = 'paragon2', maker = 'Enus', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['casco'] = { name = 'Casco', maker = 'Lampadati', price = 355000, trunk = 50, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['patriot'] = { name = 'Patriot', maker = 'Mammoth', price = 250000, trunk = 70, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['mesa3'] = { name = 'Mesa3', maker = 'Canis', price = 200000, trunk = 60, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['yosemite3'] = { name = 'yosemite3', maker = 'Declasse', price = 400000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['scramjet'] = { name = 'scramjet', maker = 'Declasse', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Super', banned = false },
    ['nightshade'] = { name = 'Nightshade', maker = 'Imponte', price = 270000, trunk = 30, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['formula2'] = { name = 'formula2', maker = 'Ocelot', price = 400000, trunk = 0, glove = 0, type = 'cars', class = 'Sports', banned = false },
    ['vapidlow'] = { name = 'vapidlow', maker = 'Vapid', price = 1000000, trunk = 0, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['veto2'] = { name = 'Veto 2', maker = 'Dinka', price = 200000, trunk = 4, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['rumpo3'] = { name = 'Rumpo3', maker = 'Bravado', price = 350000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['verus'] = { name = 'Verus', maker = 'Dinka', price = 200000, trunk = 4, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['pfister811'] = { name = 'Pfister811', maker = 'Pfister', price = 530000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['feltzer3'] = { name = 'Feltzer3', maker = 'Benefactor', price = 300000, trunk = 40, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['buccaneer'] = { name = 'Buccaneer', maker = 'Albany', price = 130000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['hermes'] = { name = 'Hermes', maker = 'Albany', price = 280000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['guardian'] = { name = 'Guardian', maker = 'Vapid', price = 500000, trunk = 150, glove = 15, type = 'cars', class = 'industrial', banned = false },
    ['dubsta3'] = { name = 'Dubsta3', maker = 'Benefactor', price = 300000, trunk = 90, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['clique'] = { name = 'Clique', maker = 'Vapid', price = 360000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['reaper'] = { name = 'Reaper', maker = 'Pegassi', price = 620000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['buccaneer2'] = { name = 'Buccaneer2', maker = 'Albany', price = 250000, trunk = 60, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['zorrusso'] = { name = 'zorrusso', maker = 'Pegassi', price = 400000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['fmj'] = { name = 'Fmj', maker = 'Vapid', price = 520000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['buffalo2'] = { name = 'Buffalo2', maker = 'Bravado', price = 300000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['z190'] = { name = 'Z190', maker = 'Karin', price = 350000, trunk = 40, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['schafter3'] = { name = 'Schafter3', maker = 'Benefactor', price = 275000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['jester'] = { name = 'Jester', maker = 'Dinka', price = 450000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['sandking'] = { name = 'Sandking', maker = 'Vapid', price = 300000, trunk = 120, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['premier'] = { name = 'Premier', maker = 'Declasse', price = 35000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['washington'] = { name = 'Washington', maker = 'Albany', price = 130000, trunk = 60, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['cognoscenti'] = { name = 'Cognoscenti', maker = 'Enus', price = 280000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['contender'] = { name = 'Contender', maker = 'Vapid', price = 500000, trunk = 80, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['torero'] = { name = 'Torero', maker = 'Pegassi', price = 160000, trunk = 30, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['t20'] = { name = 'T20', maker = 'Progen', price = 670000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['cogcabrio'] = { name = 'Cogcabrio', maker = 'Enus', price = 130000, trunk = 60, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['openwheel1'] = { name = 'openwheel1', maker = 'Benefactor', price = 400000, trunk = 0, glove = 0, type = 'cars', class = 'Sports', banned = false },
    ['formula'] = { name = 'formula', maker = 'Progen Dinka', price = 400000, trunk = 0, glove = 0, type = 'cars', class = 'Sports', banned = false },
    ['neo'] = { name = 'neo', maker = 'Vysser', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['tailgater2'] = { name = 'tailgater2', maker = 'Obey', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['mamba'] = { name = 'Mamba', maker = 'Declasse', price = 300000, trunk = 50, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['italigtb2'] = { name = 'Italigtb2', maker = 'Progen', price = 610000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['gp1'] = { name = 'Gp1', maker = 'Progen', price = 495000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['cog552'] = { name = 'Cog552', maker = 'Enus', price = 400000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['fugitive'] = { name = 'Fugitive', maker = 'Cheval', price = 50000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['primo'] = { name = 'Primo', maker = 'Albany', price = 130000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['infernus'] = { name = 'Infernus', maker = 'Pegassi', price = 470000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['bobcatxl'] = { name = 'Bobcatxl', maker = 'Vapid', price = 260000, trunk = 100, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['bison'] = { name = 'Bison', maker = 'Bravado', price = 220000, trunk = 70, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['everon2'] = { name = 'everon2', maker = 'Karin', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['banshee2'] = { name = 'Banshee2', maker = 'Bravado', price = 370000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['emperor'] = { name = 'Emperor', maker = 'Albany', price = 50000, trunk = 60, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['verlierer2'] = { name = 'Verlierer2', maker = 'Bravado', price = 380000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['monroe'] = { name = 'Monroe', maker = 'Pegassi', price = 260000, trunk = 20, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['sadler'] = { name = 'Sadler', maker = 'Vapid', price = 180000, trunk = 70, glove = 15, type = 'cars', class = 'utility', banned = false },
    ['ninef'] = { name = 'Ninef', maker = 'Obey', price = 290000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['sabregt'] = { name = 'Sabregt', maker = 'Declasse', price = 260000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['raptor'] = { name = 'Raptor', maker = 'Bf', price = 300000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['kuruma2'] = { name = 'Kuruma Blindado', maker = 'Karin', price = 1000000, trunk = 90, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['xls'] = { name = 'Xls', maker = 'Benefactor', price = 300000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['dominator'] = { name = 'Dominator', maker = 'Vapid', price = 250000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['prairie'] = { name = 'Prairie', maker = 'Bollokan', price = 1000, trunk = 25, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['mule3'] = { name = 'Mule3', maker = 'Maibatsu', price = 1500000, trunk = 700, glove = 15, type = 'cars', class = 'commercial', banned = false },
    ['vigero'] = { name = 'Vigero', maker = 'Declasse', price = 170000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['cognoscenti2'] = { name = 'Cognoscenti2', maker = 'Enus', price = 400000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['brioso2'] = { name = 'Brioso2', maker = 'Grotti', price = 25000, trunk = 30, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['rocoto'] = { name = 'Rocoto', maker = 'Obey', price = 110000, trunk = 60, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['osiris'] = { name = 'Osiris', maker = 'Pegassi', price = 460000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['surano'] = { name = 'Surano', maker = 'Benefactor', price = 310000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['zentorno'] = { name = 'Zentorno', maker = 'Pegassi', price = 920000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['schafter5'] = { name = 'Schafter5', maker = 'Benefactor', price = 275000, trunk = 50, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['youga'] = { name = 'Youga', maker = 'Bravado', price = 260000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['shotaro'] = { name = 'Shotaro', maker = 'Nagasaki', price = 1000000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['tempesta'] = { name = 'Tempesta', maker = 'Pegassi', price = 600000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['peyote'] = { name = 'Peyote', maker = 'Vapid', price = 150000, trunk = 50, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['faction'] = { name = 'Faction', maker = 'Willard', price = 150000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['gauntlet5'] = { name = 'Gauntlet5', maker = 'Bravado', price = 245000, trunk = 40, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['ztype'] = { name = 'Ztype', maker = 'Truffade', price = 400000, trunk = 20, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['italirsx'] = { name = 'italirsx', maker = 'Grotti', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['pariah'] = { name = 'Pariah', maker = 'Ocelot', price = 500000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['xls2'] = { name = 'Xls2', maker = 'Benefactor', price = 350000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['blista2'] = { name = 'Blista2', maker = 'Dinka', price = 100000, trunk = 40, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['trophytruck'] = { name = 'Trophytruck', maker = 'Vapid', price = 1000000, trunk = 20, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['dilettante'] = { name = 'Dilettante', maker = 'Karin', price = 60000, trunk = 30, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['vectre'] = { name = 'vectre', maker = 'Emperor', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['outlaw'] = { name = 'Outlaw', maker = 'Nagasaki', price = 500000, trunk = 40, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['nightshark'] = { name = 'nightshark', maker = 'HVY', price = 700000, trunk = 30, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['le7b'] = { name = 'Le7b', maker = 'Annis', price = 700000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['swinger'] = { name = 'Swinger', maker = 'Ocelot', price = 250000, trunk = 20, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['gb200'] = { name = 'Gb200', maker = 'Vapid', price = 195000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['tigon'] = { name = 'tigon', maker = 'Lampadati', price = 400000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['warrener'] = { name = 'Warrener', maker = 'Vulcar', price = 90000, trunk = 40, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['tampa2'] = { name = 'Tampa2', maker = 'Declasse', price = 200000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['slamvan'] = { name = 'Slamvan', maker = 'Vapid', price = 180000, trunk = 100, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['buffalo3'] = { name = 'Buffalo3', maker = 'Bravado', price = 300000, trunk = 50, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['surge'] = { name = 'Surge', maker = 'Cheval', price = 110000, trunk = 60, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['entityxf'] = { name = 'Entityxf', maker = 'överflöd', price = 460000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['burrito'] = { name = 'Burrito', maker = 'Declasse', price = 500000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['dominator2'] = { name = 'Dominator2', maker = 'Vapid', price = 230000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['sanctus'] = { name = 'Sanctus', maker = 'Liberty city cycles', price = 1000000, trunk = 20, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['baller4'] = { name = 'Baller4', maker = 'Gallivanter', price = 185000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['bifta'] = { name = 'Bifta', maker = 'Bf', price = 190000, trunk = 20, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['cheetah'] = { name = 'Cheetah', maker = 'Grotti', price = 425000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['baller5'] = { name = 'Baller5', maker = 'Gallivanter', price = 270000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['tornado2'] = { name = 'Tornado2', maker = 'Declasse', price = 160000, trunk = 60, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['comet6'] = { name = 'Comet6', maker = 'Pfister', price = 350000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['tornado'] = { name = 'Tornado', maker = 'Declasse', price = 150000, trunk = 70, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['burrito4'] = { name = 'Burrito4', maker = 'Declasse', price = 260000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['caracara2'] = { name = 'Caracara2', maker = 'Vapid', price = 670000, trunk = 100, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['voltic'] = { name = 'Voltic', maker = 'Coil', price = 300000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['gt500'] = { name = 'Gt500', maker = 'Grotti', price = 250000, trunk = 40, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['turismo2'] = { name = 'Turismo2', maker = 'Grotti', price = 250000, trunk = 30, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['sandking2'] = { name = 'Sandking2', maker = 'Vapid', price = 350000, trunk = 120, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['ninef2'] = { name = 'Ninef2', maker = 'Obey', price = 290000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['coquette2'] = { name = 'Coquette2', maker = 'Invetero', price = 285000, trunk = 40, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['rancherxl'] = { name = 'Rancherxl', maker = 'Declasse', price = 220000, trunk = 70, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['feltzer2'] = { name = 'Feltzer2', maker = 'Benefactor', price = 255000, trunk = 40, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['issi2'] = { name = 'Issi2', maker = 'Weeny', price = 75000, trunk = 20, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['tampa3'] = { name = 'tampa3', maker = 'Declasse', price = 110000, trunk = 50, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['openwheel2'] = { name = 'openwheel2', maker = 'Declasse Dinka', price = 400000, trunk = 0, glove = 0, type = 'cars', class = 'Sports', banned = false },
    ['rt3000'] = { name = 'rt3000', maker = 'Dinka', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['euros'] = { name = 'euros', maker = 'Annis', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['utillitruck3'] = { name = 'Utillitruck3', maker = 'Vapid', price = 180000, trunk = 120, glove = 15, type = 'cars', class = 'utility', banned = true },
    ['seven70'] = { name = 'Seven70', maker = 'Dewbauchee', price = 370000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['nero'] = { name = 'Nero', maker = 'Truffade', price = 450000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['tornado6'] = { name = 'Tornado6', maker = 'Declasse', price = 250000, trunk = 50, glove = 15, type = 'cars', class = 'sportsclassics', banned = false },
    ['taipan'] = { name = 'Taipan', maker = 'Cheval', price = 400000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['mesa'] = { name = 'Mesa', maker = 'Canis', price = 90000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['specter2'] = { name = 'Specter2', maker = 'Dewbauchee', price = 355000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['xa21'] = { name = 'Xa21', maker = 'Ocelot', price = 500000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['issi3'] = { name = 'Issi3', maker = 'Weeny', price = 190000, trunk = 20, glove = 15, type = 'cars', class = 'compacts', banned = false },
    ['stretch'] = { name = 'Stretch', maker = 'Dundreary', price = 1000000, trunk = 60, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['vamos'] = { name = 'Vamos', maker = 'Declasse', price = 185000, trunk = 60, glove = 15, type = 'cars', class = 'muscle', banned = false },
    ['benson'] = { name = 'Caminhão 1 Tonelada', maker = 'Vapid', price = 1000000, trunk = 1000, glove = 15, type = 'cars', class = 'commercial', banned = false },
    ['neon'] = { name = 'Neon', maker = 'Pfister', price = 370000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['freecrawler'] = { name = 'Freecrawler', maker = 'Canis', price = 350000, trunk = 50, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['rentalbus'] = { name = 'Ônibus Escolinha', maker = 'Brute', price = 0, trunk = 100, glove = 15, type = 'cars', class = 'service', banned = false },
    ['tezeract'] = { name = 'Tezeract', maker = 'Pegassi', price = 920000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
    ['fq2'] = { name = 'Fq2', maker = 'Fathom', price = 110000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['rebel2'] = { name = 'Rebel2', maker = 'Karin', price = 250000, trunk = 100, glove = 15, type = 'cars', class = 'offroad', banned = false },
    ['specter'] = { name = 'Specter', maker = 'Dewbauchee', price = 320000, trunk = 20, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['asterope'] = { name = 'Asterope', maker = 'Karin', price = 65000, trunk = 30, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['landstalker2'] = { name = 'Landstalker2', maker = 'Dundreary', price = 450000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['toros'] = { name = 'Toros', maker = 'Pegassi', price = 350000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['calico'] = { name = 'calico', maker = 'Karin', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['serrano'] = { name = 'Serrano', maker = 'Benefactor', price = 150000, trunk = 50, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['paradise'] = { name = 'Paradise', maker = 'Bravado', price = 260000, trunk = 120, glove = 15, type = 'cars', class = 'vans', banned = false },
    ['penumbra2'] = { name = 'penumbra2', maker = 'Maibatsu', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'Sports', banned = false },
    ['jackal'] = { name = 'Jackal', maker = 'Ocelot', price = 60000, trunk = 50, glove = 15, type = 'cars', class = 'coupes', banned = false },
    ['elegy2'] = { name = 'Elegy2', maker = 'Annis', price = 355000, trunk = 30, glove = 15, type = 'cars', class = 'sports', banned = false },
    ['squaddie'] = { name = 'squaddie', maker = 'Mammoth', price = 400000, trunk = 30, glove = 15, type = 'cars', class = 'suvs', banned = false },
    ['stanier'] = { name = 'Stanier', maker = 'Vapid', price = 15000, trunk = 60, glove = 15, type = 'cars', class = 'sedans', banned = false },
    ['tyrus'] = { name = 'Tyrus', maker = 'Progen', price = 400000, trunk = 20, glove = 15, type = 'cars', class = 'super', banned = false },
------------------------------------------------------------------------------------------------------------------------
-- MOTOS
------------------------------------------------------------------------------------------------------------------------
    ['cliffhanger'] = { name = 'Cliffhanger', maker = 'Western motorcycle company', price = 310000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['bati'] = { name = 'Bati', maker = 'Pegassi', price = 370000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['double'] = { name = 'Double', maker = 'Dinka', price = 350000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['innovation'] = { name = 'Innovation', maker = 'Liberty city cycles', price = 250000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['bati2'] = { name = 'Bati2', maker = 'Pegassi', price = 300000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['ruffian'] = { name = 'Ruffian', maker = 'Pegassi', price = 345000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['carbonrs'] = { name = 'Carbonrs', maker = 'Nagasaki', price = 370000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['vindicator'] = { name = 'Vindicator', maker = 'Dinka', price = 340000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['avarus'] = { name = 'Avarus', maker = 'Liberty city cycles', price = 200000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['blazer4'] = { name = 'Blazer4', maker = 'Nagasaki', price = 370000, trunk = 20, glove = 15, type = 'motorcycles', class = 'offroad', banned = true },
    ['oppressor'] = { name = 'oppressor', maker = 'Pegassi', price = 300000, trunk = 0, glove = 0, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['akuma'] = { name = 'Akuma', maker = 'Dinka', price = 850000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['oppressor2'] = { name = 'oppressor2', maker = 'Pegassi', price = 300000, trunk = 0, glove = 0, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['blazer'] = { name = 'Blazer', maker = 'Nagasaki', price = 230000, trunk = 20, glove = 15, type = 'motorcycles', class = 'offroad', banned = true },
    ['bagger'] = { name = 'Bagger', maker = 'Western motorcycle company', price = 300000, trunk = 40, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['daemon2'] = { name = 'Daemon2', maker = 'Western motorcycle company', price = 150000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['powersurge'] = { name = 'powersurge', maker = 'Western Motorcycle Company', price = 300000, trunk = 15, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['vader'] = { name = 'Vader', maker = 'Shitzu', price = 220000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['esskey'] = { name = 'Esskey', maker = 'Pegassi', price = 50000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['defiler'] = { name = 'Defiler', maker = 'Shitzu', price = 460000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['diablous'] = { name = 'Diablous', maker = 'Western Motorcycle Company', price = 430000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['sanchez2'] = { name = 'Sanchez2', maker = 'Maibatsu', price = 125000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['wolfsbane'] = { name = 'Wolfsbane', maker = 'Western motorcycle company', price = 290000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['lectro'] = { name = 'Lectro', maker = 'Principe', price = 380000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['faggio3'] = { name = 'Faggio3', maker = 'Pegassi', price = 7500, trunk = 30, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['manchez3'] = { name = 'manchez3', maker = 'Maibatsu', price = 300000, trunk = 15, glove = 0, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['manchez2'] = { name = 'manchez2', maker = 'Maibatsu', price = 300000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['sovereign'] = { name = 'Sovereign', maker = 'Western motorcycle company', price = 285000, trunk = 50, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['hexer'] = { name = 'Hexer', maker = 'Liberty city cycles', price = 250000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['enduro'] = { name = 'Enduro', maker = 'Dinka', price = 50000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['diablous2'] = { name = 'Diablous2', maker = 'Western Motorcycle Company', price = 460000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['rrocket'] = { name = 'rrocket', maker = 'Western Motorcycle Company', price = 300000, trunk = 0, glove = 0, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['nemesis'] = { name = 'Nemesis', maker = 'Principe', price = 345000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['manchez'] = { name = 'Manchez', maker = 'Maibatsu', price = 355000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['fcr'] = { name = 'Fcr', maker = 'Pegassi', price = 390000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['hakuchou'] = { name = 'Hakuchou', maker = 'Shitzu', price = 380000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['bf400'] = { name = 'Bf400', maker = 'Nagasaki', price = 150000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['faggio'] = { name = 'Faggio', maker = 'Pegassi', price = 5000, trunk = 30, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['faggio2'] = { name = 'Faggio2', maker = 'Pegassi', price = 5000, trunk = 30, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['thrust'] = { name = 'Thrust', maker = 'Dinka', price = 375000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['chimera'] = { name = 'Chimera', maker = 'Nagasaki', price = 345000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['ratbike'] = { name = 'Ratbike', maker = 'Western motorcycle company', price = 230000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['gargoyle'] = { name = 'Gargoyle', maker = 'Western motorcycle company', price = 345000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['zombieb'] = { name = 'Zombieb', maker = 'Steel horse', price = 300000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['stryder'] = { name = 'stryder', maker = 'Nagasaki', price = 300000, trunk = 15, glove = 0, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['zombiea'] = { name = 'Zombiea', maker = 'Western motorcycle company', price = 290000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['hakuchou2'] = { name = 'Hakuchou2', maker = 'Shitzu', price = 550000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['fcr2'] = { name = 'Fcr2', maker = 'Pegassi', price = 390000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['pcj'] = { name = 'Pcj', maker = 'Shitzu', price = 50000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['nightblade'] = { name = 'Nightblade', maker = 'Liberty chop shop', price = 350000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['sanchez'] = { name = 'Sanchez', maker = 'Maibatsu', price = 185000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['vortex'] = { name = 'Vortex', maker = 'Pegassi', price = 375000, trunk = 20, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
    ['deathbike2'] = { name = 'Death Bike', maker = 'Western motorcycle company', price = 1000000, trunk = 0, glove = 15, type = 'motorcycles', class = 'motorcycles', banned = false },
------------------------------------------------------------------------------------------------------------------------
-- PLANES
------------------------------------------------------------------------------------------------------------------------
    ['swift2'] = { name = 'Swift 2', maker = 'Buckingham', price = 0, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopter', banned = false },
    ['swift'] = { name = 'Swift', maker = 'Buckingham', price = 0, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopter', banned = false },
    ['frogger'] = { name = 'Frogger', maker = 'Maibatsu', price = 1000000, trunk = 0, glove = 15, type = 'helicopter', class = 'helicopters', banned = true },
    ['supervolito'] = { name = 'Supervolito', maker = 'Buckingham', price = 1000, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopters', banned = false },
    ['cargobob'] = { name = 'CSC Cargobob', maker = 'Western company', price = 1000000, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopters', banned = false },
    ['buzzard2'] = { name = 'Buzzard 2', maker = 'Nagasaki', price = 1000000, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopters', banned = false },
    ['cargobob2'] = { name = 'Cargo Bob', maker = 'Western company', price = 1000000, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopters', banned = false },
------------------------------------------------------------------------------------------------------------------------
-- WORK
------------------------------------------------------------------------------------------------------------------------
    ['avisa'] = { name = 'avisa', maker = 'Kraken', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['toro'] = { name = 'Toro', maker = 'Lampadati', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['jetmax'] = { name = 'Jetmax', maker = 'Grotti', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['vestra'] = { name = 'Vestra', maker = 'Buckingham', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['cog55'] = { name = 'Cog55', maker = 'Enus', price = 200000, trunk = 50, glove = 15, type = 'work', class = 'sedans', banned = false },
    ['youga2'] = { name = 'Youga2', maker = 'Bravado', price = 1000, trunk = 80, glove = 15, type = 'work', class = 'vans', banned = false },
    ['coach'] = { name = 'Coach', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'service', banned = true },
    ['riot'] = { name = 'Blindado', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['mule'] = { name = 'Mule', maker = 'Maibatsu', price = 500000, trunk = 0, glove = 15, type = 'work', class = 'commercial', banned = true },
    ['flatbed'] = { name = 'Reboque', maker = 'MTL', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'industrial', banned = true },
    ['superd'] = { name = 'Superd', maker = 'Enus', price = 200000, trunk = 50, glove = 15, type = 'work', class = 'sedans', banned = false },
    ['ratloader'] = { name = 'Caminhão', maker = 'Bravado', price = 80000, trunk = 80, glove = 15, type = 'work', class = 'muscle', banned = true },
    ['towtruck2'] = { name = 'Towtruck2', maker = 'Vapid', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['daemon'] = { name = 'Daemon', maker = 'Western motorcycle company', price = 75000, trunk = 20, glove = 15, type = 'work', class = 'motorcycles', banned = false },
    ['miljet'] = { name = 'Miljet', maker = 'Western company', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['bmx'] = { name = 'Bmx', maker = 'Bmx', price = 1, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['ambulance'] = { name = 'Ambulância', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['primo2'] = { name = 'Primo2', maker = 'Albany', price = 100000, trunk = 60, glove = 15, type = 'work', class = 'sedans', banned = false },
    ['boxville'] = { name = 'BoxVille', maker = 'Brute', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'vans', banned = true },
    ['ratloader2'] = { name = 'Ratloader2', maker = 'Bravado', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'muscle', banned = false },
    ['felon2'] = { name = 'Felon2', maker = 'Lampadati', price = 1000, trunk = 40, glove = 15, type = 'work', class = 'coupes', banned = false },
    ['tribike3'] = { name = 'Tribike3', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['phantom'] = { name = 'Phantom', maker = 'Jobuilt', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'commercial', banned = true },
    ['cruiser'] = { name = 'Cruiser', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['polmav'] = { name = 'Polmav', maker = 'Buckingham', price = 0, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['speeder'] = { name = 'Speeder', maker = 'Pegassi', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['supervolito2'] = { name = 'Supervolito2', maker = 'Buckingham', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'helicopters', banned = true },
    ['btype'] = { name = 'Btype', maker = 'Albany', price = 200000, trunk = 40, glove = 15, type = 'work', class = 'sportsclassics', banned = false },
    ['boxville4'] = { name = 'BoxVille4', maker = 'Brute', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'vans', banned = true },
    ['squalo'] = { name = 'Squalo', maker = 'Grotti', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['speedo'] = { name = 'Speedo', maker = 'Vapid', price = 200000, trunk = 120, glove = 15, type = 'work', class = 'vans', banned = false },
    ['slamvan2'] = { name = 'Slamvan2', maker = 'Vapid', price = 200000, trunk = 100, glove = 15, type = 'work', class = 'muscle', banned = false },
    ['tornado5'] = { name = 'Tornado5', maker = 'Declasse', price = 200000, trunk = 60, glove = 15, type = 'work', class = 'sportsclassics', banned = false },
    ['gburrito'] = { name = 'GBurrito', maker = 'Declasse', price = 500000, trunk = 100, glove = 15, type = 'work', class = 'vans', banned = false },
    ['trailerlogs'] = { name = 'Woods', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['volatus'] = { name = 'Volatus', maker = 'Buckingham', price = 1000000, trunk = 1000, glove = 15, type = 'work', class = 'helicopters', banned = true },
    ['seashark3'] = { name = 'Seashark3', maker = 'Speedophile', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['fbi2'] = { name = 'Granger FBI', maker = 'Declasse', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['marquis'] = { name = 'Marquis', maker = 'Dinka', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['graintrailer'] = { name = 'GrainTrailer', maker = 'Brute', price = 1000, trunk = 500, glove = 15, type = 'work', class = 'utility', banned = false },
    ['tvtrailer'] = { name = 'Show', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['tanker2'] = { name = 'Gas', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['toro2'] = { name = 'Toro2', maker = 'Lampadati', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['maverick'] = { name = 'Maverick', maker = 'Western company', price = 100000, trunk = 1000, glove = 15, type = 'work', class = 'helicopters', banned = true },
    ['tiptruck'] = { name = 'Tiptruck', maker = 'Brute', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'industrial', banned = false },
    ['trash2'] = { name = 'Caminhão Lixo', maker = 'Brute', price = 1000, trunk = 80, glove = 15, type = 'work', class = 'utility', banned = false },
    ['towtruck'] = { name = 'Towtruck', maker = 'Vapid', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['rebel'] = { name = 'Rebel', maker = 'Karin', price = 1000, trunk = 80, glove = 15, type = 'work', class = 'offroad', banned = false },
    ['rubble'] = { name = 'Caminhão', maker = 'Jobuilt', price = 1000, trunk = 200, glove = 15, type = 'work', class = 'industrial', banned = false },
    ['caddy'] = { name = 'Caddy', maker = 'Work', price = 180000, trunk = 120, glove = 15, type = 'work', class = 'utility', banned = true },
    ['stafford'] = { name = 'Stafford', maker = 'Enus', price = 150000, trunk = 40, glove = 15, type = 'work', class = 'sedans', banned = false },
    ['dinghy'] = { name = 'Dinghy', maker = 'Nagasaki', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['mammatus'] = { name = 'Mammatus', maker = 'Jobuilt', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['armytanker'] = { name = 'Diesel', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['police4'] = { name = 'Cruiser FBI', maker = 'Vapid', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['fbi'] = { name = 'Buffalo FBI', maker = 'Declasse', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['suntrap'] = { name = 'Suntrap', maker = 'Shitzu', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['bus'] = { name = 'Ônibus', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'service', banned = true },
    ['faction2'] = { name = 'Faction2', maker = 'Willard', price = 200000, trunk = 40, glove = 15, type = 'work', class = 'muscle', banned = false },
    ['cuban800'] = { name = 'Cuban800', maker = 'Western company', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['velum2'] = { name = 'Velum2', maker = 'Jobuilt', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['boxville2'] = { name = 'BoxVille2', maker = 'Brute', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'vans', banned = true },
    ['seashark2'] = { name = 'seashark2', maker = 'Kraken', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'Speedophile', banned = true },
    ['tribike'] = { name = 'Tribike', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['tropic2'] = { name = 'Tropic2', maker = 'Grotti', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['bison2'] = { name = 'Bison2', maker = 'Bravado', price = 0, trunk = 0, glove = 15, type = 'work', class = 'vans', banned = true },
    ['luxor2'] = { name = 'Luxor Dourado', maker = 'Western company', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['tropic'] = { name = 'Tropic', maker = 'Grotti', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['packer'] = { name = 'Packer', maker = 'MTL', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'commercial', banned = true },
    ['seasparrow'] = { name = 'Paramédico Helicóptero Água', maker = 'Maibatsu', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'helicopters', banned = true },
    ['taxi'] = { name = 'Taxi', maker = 'Vapid', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'service', banned = true },
    ['tribike2'] = { name = 'Tribike2', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['tr4'] = { name = 'Carga de Carros', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['tractor2'] = { name = 'Tractor2', maker = 'Stanley', price = 1000, trunk = 80, glove = 15, type = 'work', class = 'utility', banned = false },
    ['chino2'] = { name = 'Chino2', maker = 'Vapid', price = 100000, trunk = 60, glove = 15, type = 'work', class = 'muscle', banned = false },
    ['policeb'] = { name = 'Harley Davidson', maker = 'Western motorcycle company', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['pbus'] = { name = 'PBus', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['bison3'] = { name = 'Bison3', maker = 'Bravado', price = 0, trunk = 0, glove = 15, type = 'work', class = 'vans', banned = true },
    ['utillitruck'] = { name = 'Utillitruck', maker = 'Vapid', price = 180000, trunk = 120, glove = 15, type = 'work', class = 'utility', banned = true },
    ['scorcher'] = { name = 'Scorcher', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
}

config.garages = {
    {
        coords = vector3(55.54286, -876.1714, 30.6615), 
        rule = 'carOnly',
        points = {
            vector4(50.5055, -873.7319, 30.42566, 155.9055),
            vector4(47.38022, -872.2681, 30.4425, 155.9055),
            vector4(44.09671, -870.9231, 30.45935, 155.9055)
        }
    },
    {
        coords = vector3(44.33407, -842.2154, 31.1333), 
        rule = 'carOnly',
        points = {
            vector4(53.48572, -847.2396, 30.83008, 153.0709),
            vector4(56.7033, -848.2813, 30.81323, 153.0709),
            vector4(59.68352, -849.5077, 30.79639, 150.2362),
            vector4(63.01978, -850.9583, 30.79639, 161.5748)
        }
    },
}

config.rules = {
    ['carOnly'] = {
        ['show_classes'] = nil,
        ['hide_classes'] = { ['planes'] = true, ['helicopters'] = true, ['boats'] = true }
    },
    ['heliOnly'] = {
        ['show_classes'] = { ['helicopters'] = true },
        ['hide_classes'] = nil
    },
    ['planeOnly'] = {
        ['show_classes'] = { ['planes'] = true },
        ['hide_classes'] = nil
    },
    ['boatsOnly'] = {
        ['show_classes'] = { ['boats'] = true },
        ['hide_classes'] = nil
    },
}

config.hashes = {}

for vname, data in pairs(config.vehicles) do
	if (data.hash) then
		config.hashes[data.hash] = vname
	else		
		local model = GetHashKey(vname)
		config.vehicles[vname].hash = model
		config.hashes[model] = vname
	end
end