Config = Config or {}

Config.Webhooks = {
	Ban = "https://discord.com/api/webhooks/1154626977916006490/Ta8CUDcWUaOs2oWy6YZZ4JBJO6jvhlsp5T0mHP_4SCDCeAG0almhmij1wsmWpj9r00qA",
	Suspicious = "https://discord.com/api/webhooks/1154627072497565727/fAwezzBJWO5BVtPYfM_JS2nfgGcqSIinkOcpBtFemDWdIdV6h_WD1ahI0zplttQWDeQY",
	Wall = "https://discord.com/api/webhooks/1154626712194269306/mF0vlYRoAbuAdgPGdn74xNdoCVSx4mU1ED9quCRr-qO6CqpzAwofq8zuNJmELr_de_jo",
	ScreenShot = "https://discord.com/api/webhooks/1154626771216502804/eO4Gsu2xJrdhIhcGV0j7xqxejeMiNgWQtL1eHFH6Jriw-vt2zmh4z1NwrFxQ8_ZklFBy",
	BanHistory = "https://discord.com/api/webhooks/1154626840825172060/hFwqxU-eg-Vrs7l9IHwQUo9gY8FwZM1SGU5406Dwg9iyRiYk6_dc0dCUChdC0T4XQd6K",
}



Config.Detections = {
	["KB_01"] = true, --[[ true/false (true = ban, false = suspeito) ]]
	["POST_FX"] = true,
	["Explosive Bullets"] = false,
	["Weapon Damage Multiplier"] = true,
	["Weapon Spawn"] = true,
	["Generic Menu Detection"] = false,
	["Player Damage Multiplier"] = true,
	["Player Crash"] = true,
	["Spawn de Objetos"] = false,
	["Spawn de Veiculos"] = false,
	["Spawn de NPC"] = false,
	["Mod Menu 01"] = true,
	["Mod Menu 02"] = true,
	["Anti HS"] = true,
	["Injeção de Menu"] = true,
	["Spectate"] = false,
	["Semi God"] = false,
	["Particles"] = false,
	["Fake Shoot"] = true,
	["Mod Menu 09"] = true,

	["Stop AntiCheat 01"] = true,
	["Stop AntiCheat 02"] = true,
	["Stop AntiCheat 05"] = true,
	["Generic Menu Detection"] = true,
	["Mod Menu [K-R]"] = true,
	["Monster Menu 03"] = true,

	["Weapon Spawn 03"] = true,
	["Citizen - Varar Parede"] = true,
	["No Clip 05"] = true,
	["No Clip 07"] = true,
	["Citizen - Sem Rolamento"] = true,
	["Citizen - Municao Infinita"] = true,
	["Ammo Spawn"] = false,
	["Silent Aim (Citizen)"] = true,
	["Stop vRP"] = true,
	["Manipulacao de Eventos 03"] = true,
	["Manipulando vRP:tunnel_req"] = true,
}

Config.BanThreeshold = 15

Config.DefaultDamages = {
	[GetHashKey("WEAPON_CARBINERIFLE")] = 2.0,
}

Config.NotifyAdmins = true

Config.FooterBanText = "\nPara recorrer entre em nosso Discord! discord.gg/zerocity"

Config.ImageCDN = "https://discord.com/api/webhooks/1144460681605828788/pVc2ykz_y9pPeabMb-Gp2iEoLdDwG-Ibpi0zTBalIhlbC2evOvA0IPHqFqvePA7JZFfC"


Config.WeaponsList = {
	"WEAPON_KNIFE",
	"WEAPON_NIGHTSTICK",
	"WEAPON_HAMMER",
	"WEAPON_BAT",
	"WEAPON_CROWBAR",
	"WEAPON_GOLFCLUB",
	"WEAPON_BOTTLE",
	"WEAPON_DAGGER",
	"WEAPON_HATCHET",
	"WEAPON_KNUCKLEDUSTER",
	"WEAPON_MACHETE",
	"WEAPON_FLASHLIGHT",
	"WEAPON_SWITCHBLADE",
	"WEAPON_POOLCUE",
	"WEAPON_WRENCH",
	"WEAPON_BATTLEAXE",
	"WEAPON_PISTOL",
	"WEAPON_COMBATPISTOL",
	"WEAPON_APPISTOL",
	"WEAPON_PISTOL50",
	"WEAPON_SNSPISTOL",
	"WEAPON_HEAVYPISTOL",
	"WEAPON_VINTAGEPISTOL",
	"WEAPON_MARKSMANPISTOL",
	"WEAPON_VINTAGEPISTOL",
	"WEAPON_PISTOL_MK2",
	"WEAPON_SNSPISTOL_MK2",
	"WEAPON_FLAREGUN",
	"WEAPON_STUNGUN",
	"WEAPON_REVOLVER",
	"WEAPON_MICROSMG",
	"WEAPON_MACHINEPISTOL",
	"WEAPON_SMG",
	"WEAPON_SMGMK2",
	"WEAPON_ASSAULTSMG",
	"WEAPON_COMBATPDW",
	"WEAPON_MG",
	"WEAPON_COMBATMG",
	"WEAPON_COMBATMGMK2",
	"WEAPON_GUSENBERG",
	"WEAPON_MINISMG",
	"WEAPON_ASSAULTRIFLE",
	"WEAPON_ASSAULTRIFLE_MK2",
	"WEAPON_CARBINERIFLE",
	"WEAPON_CARBINERIFLE_MK2",
	"WEAPON_ADVANCEDRIFLE",
	"WEAPON_SPECIALCARBINE",
	"WEAPON_BULLPUPRIFLE",
	"WEAPON_COMPACTRIFLE",
	"WEAPON_SNIPERRIFLE",
	"WEAPON_HEAVYSNIPER",
	"WEAPON_HEAVYSNIPERMK2",
	"WEAPON_MARKSMANRIFLE",
	"WEAPON_PUMPSHOTGUN",
	"WEAPON_SAWNOFFSHOTGUN",
	"WEAPON_BULLPUPSHOTGUN",
	"WEAPON_ASSAULTSHOTGUN",
	"WEAPON_MUSKET",
	"WEAPON_HEAVYSHOTGUN",
	"WEAPON_DOUBLEBARRELSHOTGUN",
	"WEAPON_AUTOSHOTGUN",
	"WEAPON_GRENADELAUNCHER",
	"WEAPON_RPG",
	"WEAPON_FIREWORK",
	"WEAPON_RAILGUN",
	"WEAPON_HOMINGLAUNCHER",
	"WEAPON_GRENADELAUNCHERSMOKE",
	"WEAPON_COMPACTLAUNCHER",
	"WEAPON_GRENADE",
	"WEAPON_STICKYBOMB",
	"WEAPON_PROXIMITYMINE",
	"WEAPON_BZGAS",
	"WEAPON_MOLOTOV",
	"GADGET_PARACHUTE",
	"WEAPON_FIREEXTINGUISHER",
	"WEAPON_PETROLCAN",
	"WEAPON_FLARE",
	"WEAPON_BALL",
	"WEAPON_SNOWBALL",
	"WEAPON_SMOKEGRENADE",
	"WEAPON_PIPEBOMB",
	"WEAPON_NAVYREVOLVER",
	"WEAPON_MILITARYRIFLE",
	"WEAPON_HAZARDCAN",
	"WEAPON_GADGETPISTOL",
	"WEAPON_COMBATSHOTGUN",
	"WEAPON_CERAMICPISTOL",
}
