zero._prepare('zero_bank/getPix', 'select chave from zero_pix where user_id = @user_id')
zero._prepare('zero_bank/editPix', 'update zero_pix set chave = @chave where user_id = @user_id')
zero._prepare('zero_bank/checkPix', 'select chave from zero_pix where chave = @chave')
zero._prepare('zero_bank/addPix', 'insert zero_pix (user_id, chave) values (@user_id, @chave)')
zero._prepare('zero_bank/delPix', 'delete from zero_pix where user_id = @user_id')
zero._prepare('zero_bank/addMultas', 'insert zero_fine (user_id, fine_reason, fine_value, fine_time, fine_description) values (@user_id, @reason, @value, @time, @description)')
zero._prepare('zero_bank/getMultas', 'select * from zero_fine where user_id = @user_id')
zero._prepare('zero_bank/getMulta', 'select * from zero_fine where id = @multa_id')
zero._prepare('zero_bank/delMulta', 'delete from zero_fine where user_id = @user_id and id = @multa_id')
zero._prepare('zero_bank/delAllMultas', 'delete from zero_fine where user_id = @user_id')