zero._prepare('zero_homes/getApartamentOwner', 'select * from homes where home like @home and user_id = @user_id and home_owner = 1')
zero._prepare('zero_homes/getApartamentOwnerWithoutUser', 'select * from homes where home like @home and home_owner = 1')
zero._prepare('zero_homes/apartamentPermissions', 'select * from homes where home like @home AND user_id = @user_id')
zero._prepare('zero_homes/getHomeOwner', 'select * from homes where home = @home AND home_owner = 1')
zero._prepare('zero_homes/buyHome', 'insert homes (user_id, home, home_owner, garages, tax, configs, vip) values (@user_id, @home, @home_owner, @garages, @tax, @configs, @vip)')
zero._prepare('zero_homes/homePermissions', 'select * from homes where home = @home AND user_id = @user_id')
zero._prepare('zero_homes/countPermissions', 'select count(*) as qtd from homes where home = @home')
zero._prepare('zero_homes/newPermissions', 'insert into homes (user_id, home, home_owner, tax, garages, configs, vip) values (@user_id, @home, @home_owner, @tax, @garages, @configs, @vip)')
zero._prepare('zero_homes/removePermissions', 'delete from homes where home = @home and user_id = @user_id')
zero._prepare('zero_homes/removeResidents', 'delete from homes where home = @home and home_owner = 0')
zero._prepare('zero_homes/updateOwner', 'update homes set user_id = @nuser_id where user_id = @user_id and home = @home')
zero._prepare('zero_homes/sellHome', 'delete from homes where home = @home')
zero._prepare('zero_homes/selectHomes', 'select * from homes where home = @home')
zero._prepare('zero_homes/updateTax', 'update homes set tax = @tax where home = @home')
zero._prepare('zero_homes/userList', 'select * from homes where user_id = @user_id and home_owner = 1')
zero._prepare('zero_homes/userHomesList', 'select * from homes where user_id = @user_id')
zero._prepare('zero_homes/updateConfig', 'update homes set configs = @configs where home = @home')
zero._prepare('zero_homes/updateGarages', 'update homes set garages = @garages where home = @home and home_owner = 1')
zero._prepare('zero_homes/addGarage', 'insert homes_garages (home, blip, spawn) values (@home, @blip, @spawn)')
zero._prepare('zero_homes/permissions', 'select * from homes where home = @home')
zero._prepare('zero_homes/getGarage', 'select * from homes_garages where home = @home')
zero._prepare('zero_homes/delGarage', 'delete from homes_garages where home = @home')
zero._prepare('zero_homes/getHomes', 'select * from homes')
zero._prepare('zero_homes/getAllHomesOwner', 'select * from homes where home_owner = 1')