zero._prepare('zero_homes/getApartamentOwner', 'select * from zero_homes where home like @home and user_id = @user_id and home_owner = 1')
zero._prepare('zero_homes/getHomeOwner', 'select * from zero_homes where home = @home AND home_owner = 1')
zero._prepare('zero_homes/buyHome', 'insert zero_homes (user_id, home, home_owner, garages, tax, configs, vip) values (@user_id, @home, @home_owner, @garages, @tax, @configs, @vip)')
zero._prepare('zero_homes/homePermissions', 'select * from zero_homes where home = @home AND user_id = @user_id')
zero._prepare('zero_homes/countPermissions', 'select count(*) as qtd from zero_homes where home = @home')
zero._prepare('zero_homes/newPermissions', 'insert into zero_homes (user_id, home, home_owner, tax, garages, configs, vip) values (@user_id, @home, @home_owner, @tax, @garages, @configs, @vip)')
zero._prepare('zero_homes/removePermissions', 'delete from zero_homes where home = @home and user_id = @user_id')
zero._prepare('zero_homes/removeResidents', 'delete from zero_homes where home = @home and home_owner = 0')
zero._prepare('zero_homes/updateOwner', 'update zero_homes set user_id = @nuser_id where user_id = @user_id and home = @home')
zero._prepare('zero_homes/sellHome', 'delete from zero_homes where home = @home')
zero._prepare('zero_homes/selectHomes', 'select * from zero_homes where home = @home')
zero._prepare('zero_homes/updateTax', 'update zero_homes set tax = @tax where home = @home')
zero._prepare('zero_homes/userList', 'select * from zero_homes where user_id = @user_id and home_owner = 1')
zero._prepare('zero_homes/updateConfig', 'update zero_homes set configs = @configs where home = @home')
zero._prepare('zero_homes/updateGarages', 'update zero_homes set garages = @garages where home = @home and home_owner = 1')
zero._prepare('zero_homes/addGarage', 'insert zero_homes_garages (home, blip, spawn) values (@home, @blip, @spawn)')
zero._prepare('zero_homes/permissions', 'select * from zero_homes where home = @home')
zero._prepare('zero_homes/getGarage', 'select * from zero_homes_garages where home = @home')